# This is a basic workflow to help you get started with Actions

name: Molecule test with Ubuntu 20 and SSL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Ansible Molecule
        # You may pin to the exact commit or the version.
        # uses: gofrolist/molecule-action@0e1ff1d6047ca4c4c12cb4887d92f1b5cc556ab7
        uses: gofrolist/molecule-action@v2.2.6
        with:
          molecule_args: "-s ubuntu20-ssl"
              
